baseURL: "http://biobanks.covid19dataportal.se/"
languageCode: "en-us"
title: "The Swedish COVID-19 Sample Collection Database"
params:
  title: "The Swedish COVID-19 Sample Collection Database"
  description: "The Swedish COVID-19 Sample Collection Database, part of the Swedish COVID-19 and Pandemic Preparedness Portal"
markup:
  goldmark:
    renderer:
      unsafe: true
taxonomies:
  material: materials
