baseURL: "http://biobanks.pathogens.se/"
languageCode: "en-us"
title: "The Swedish COVID-19 Sample Collection Database"
params:
  title: "The Swedish COVID-19 Sample Collection Database"
  description: "The Swedish COVID-19 Sample Collection Database, part of the Swedish Pathogens Portal"
markup:
  goldmark:
    renderer:
      unsafe: true
taxonomies:
  material: materials
